version: "3.8"



services:
  mysqldb:
    image: mysql:5.7
    networks:
      - springboot-db-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=devops
   
    restart: unless-stopped
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8083:80
    networks:
      - springboot-db-net
    depends_on:
      - mysqldb


  application:
    image: devops_project
    build: .
    ports:
      - "8082:8082"
    networks:
      - springboot-db-net
    depends_on:
      - mysqldb
  
  

    
    
  
networks:
  springboot-db-net: