version: "3.8"



services:
  mysqldb:
    image: mysql:5.7
    networks:
      - springboot-db-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=devops
    volumes:
      - db:/var/lib/mysql
    restart: unless-stopped

  application:
    image: devops_project
    build: .
    ports:
      - "8082:8082"
    networks:
      - springboot-db-net
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    
  
networks:
  springboot-db-net: